[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lending = "PuzF3FCpbFa3GKdaTAhw7kS5uojzrMzk2EwfsZsZ2pi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
jest_test= "npm est test"
